"""cadmus CLI entry point."""

import argparse
import os
import sys
from datetime import datetime


def main():
    parser = argparse.ArgumentParser(
        prog="cadmus",
        description="CADMUS — AI Spec Engine",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  cadmus "A compliance document tracker for financial services"
  cadmus "A tool to track oil and gas leases" --export prd
  cadmus "A risk scoring dashboard" --export engineering_handoff --out handoff.md
  cadmus --exports
        """,
    )
    parser.add_argument("idea", nargs="?", help="Raw product idea (quoted string)")
    parser.add_argument("--export", metavar="TYPE", help="Export type to generate")
    parser.add_argument("--out", metavar="FILE", help="Output file (default: stdout)")
    parser.add_argument("--exports", action="store_true", help="List available export types")
    parser.add_argument("--key", metavar="KEY", help="OpenAI API key (overrides env var)")
    args = parser.parse_args()

    if args.exports:
        from .models import ExportType
        print("\nAvailable export types:")
        for t in ExportType:
            print(f"  {t.value}")
        print()
        sys.exit(0)

    if not args.idea:
        parser.print_help()
        sys.exit(1)

    from .engine import CadmusEngine
    try:
        engine = CadmusEngine(api_key=args.key)
    except (ImportError, ValueError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"\nCADMUS — AI Spec Engine")
    print("━" * 50 + "\n")

    print("▸ EXTRACT      parsing raw idea...")
    try:
        spec = engine.create_spec(args.idea)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    s = spec.scores
    print(f"✓ Extracted: {spec.idea.objective[:80]}\n")
    print(f"  Clarity:          {s.clarity:3d}/100")
    print(f"  Completeness:     {s.completeness:3d}/100")
    print(f"  Logic Integrity:  {s.logic_integrity:3d}/100")
    print(f"  Edge Cases:       {s.edge_case:3d}/100")
    print(f"  Build Readiness:  {s.build_readiness:3d}/100  {s.label}")
    print(f"\n  {s.reasoning}\n")

    if args.export:
        print(f"▸ EXPORT       generating {args.export}...")
        try:
            output = engine.export(spec, args.export)
        except (ValueError, Exception) as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)

        if args.out:
            with open(args.out, "w") as f:
                f.write(output)
            print(f"✓ Saved to {args.out}")
        else:
            print(output)
    else:
        print("━━━ ASSEMBLED SPEC " + "━" * 31)
        print(spec.content)

    print(f"\nGenerated by CADMUS — {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
